engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 50
ratings:
  paths:
    - "lib/**/*"
exclude_paths:
  - "test/"
  - "support/"
  - "config/"
